### ISSUE TITLE
Remove offense by rubicon on spec

### ISSUE THREAD

**Issue by kurenn** [Internship2017/star_wars_ffg#48]
<img width="1266" alt="screen shot 2017-06-23 at 3 38 38 pm" src="https://user-images.githubusercontent.com/236312/27499568-18e4b334-582a-11e7-818d-df391bf5fb53.png">

**Comment by joseantoniordlmc** [comment]
This issue was already solved. Alongside the other issue it was changed on Making rubocop happy again.

**Comment by kurenn** [comment]
Can you specify which PR solved it?

**Comment by JorgeATR** [comment]
It was the "Make Rubocop happy again" request by Anapaotrev, sorry I didn't see the issue until late Friday, otherwise I would've fixed it!

**Comment by joseantoniordlmc** [comment]
PR Making rubocop happy again #51

**Comment by kvinuk** [comment]
7 Days
